Set BTR profile to be default
duraspace/bagit-support pull request #41
Opened 2020-09-29 20:00 UTC by mikejritter

Resolves: #39 

* Create BagProfile constructor which uses the beyondtherepository profile
* Rename default profile to fedora-import-export

2020-09-29 22:11 UTC, mikejritter commented
Also considering adding an additional function `public static BuiltIn from(final String identifier, final BuiltIn profile)` which will match against the `identifier` against the string "default" and return the profile supplied. This can help bridge the gap for tools like the import-export-utility which previously used the default keyword for their profile identifiers.

2020-10-12 23:57 UTC, awoods requested changes

2020-10-12 23:57 UTC, awoods commented on README.md
> +* [default](src/main/resources/profiles/fedora-import-export.json)
Is the Fedora profile still the "default"?

2020-10-13 14:17 UTC, bbranan commented on src/test/java/org/duraspace/bagit/SerializationSupportTest.java
>          // Currently the DEFAULT profile only supports application/tar, so send a file which is not a tarball
This comment should be updated (since there is no longer a DEFAULT profile)

2020-10-13 22:34 UTC, awoods approved these changes

2020-10-14 16:03 UTC, merged